FROM nginx

COPY ./default.conf /etc/nginx/conf.d/

# Expose the ports that the reverse proxy will listen on
EXPOSE 8888 9000

# Start Nginx when the container is run
CMD ["nginx", "-g", "daemon off;"]

